BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "config" (
	"DBVersion"	INTEGER NOT NULL DEFAULT 1,
	"MilesKms"	INTEGER NOT NULL DEFAULT 0,
	"Langcode"	TEXT NOT NULL DEFAULT 'en',
	"Eventname"	TEXT NOT NULL,
	"DBInitialised"	INTEGER NOT NULL DEFAULT 0,
	"DefaultStart"	TEXT NOT NULL DEFAULT '/',
	"Region"	TEXT NOT NULL DEFAULT 'United Kingdom',
	"Localtz"	TEXT NOT NULL DEFAULT 'Europe/London',
	"Decimalcomma"	INTEGER NOT NULL DEFAULT 0,
	"Hostcountry"	TEXT NOT NULL DEFAULT 'UK',
	"Locale"	TEXT NOT NULL DEFAULT 'en-GB',
	"VirtualRally"	INTEGER NOT NULL DEFAULT 0,
	"Startdate"	TEXT NOT NULL DEFAULT '2021-01-01',
	"Starttime"	TEXT NOT NULL DEFAULT '09:00',
	"Finishdate"	TEXT NOT NULL DEFAULT '2021-01-01',
	"Finishtime"	TEXT NOT NULL DEFAULT '17:00',
	"Maxhours"	INTEGER NOT NULL DEFAULT 8,
	"MaxmilesDNF"	INTEGER NOT NULL DEFAULT 0,
	"MaxmilesPenalties"	INTEGER NOT NULL DEFAULT 0,
	"MinmilesDNF"	INTEGER NOT NULL DEFAULT 0,
	"ExcessPPM"	INTEGER NOT NULL DEFAULT 0,
	"Tankrange"	INTEGER NOT NULL DEFAULT 200,
	"MinsPerStop"	INTEGER NOT NULL DEFAULT 10
);
INSERT INTO "config" VALUES (1,0,'en','IBA Rally',1,'/','United Kingdom','Europe/London',0,'UK','en-GB',0,'2021-01-01','09:00','2021-01-01','17:00',8,0,0,0,0,200,10);
COMMIT;
